default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV["DB_NAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  database: company_development


test:
  <<: *default
  database: company_test
